apiVersion: v1
kind: ReplicationController
metadata:
  name: frontend
  labels:
    name:  frontend
spec:
  replicas: 3
  selector:
    name: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: php-redis
          image: gcr.io/google_samples/gb-frontend:v3
          env:
            - name: GET_HOSTS_FROM
              value: env
          ports:
            - containerPort: 80
