apiVersion: v1
kind: Pod
metadata:
  name: host-network-mode
spec:
  containers:
  - name: host-network-mode
    image: nginx
    ports:
      - containerPort: 80
        protocol: TCP
        name: web
  hostNetwork: true
